version: '3.7'

networks:
  loki:

services:
  django:
    image: "skyline918/django-time-app"
    ports:
      - 8000:8000
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./config:/etc/promtail/config/
    command: -config.file=/etc/promtail/config/docker-promtail.yml
    ports:
      - "9080:9080"
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki

  prometheus:
    image: prom/prometheus:v2.7.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/app.cfg
    networks:
      - loki
    command: >-
      --config.file=/app.cfg/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.console.libraries=/usr/share/prometheus/console_libraries
      --web.console.templates=/usr/share/prometheus/consoles