global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
scrape_configs:

  - job_name: 'loki'
    static_configs:
      - targets: [ 'loki:3100' ]

  - job_name: 'self'
    static_configs:
      - targets: [ 'localhost:9090' ]
