server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

- job_name: containers

  static_configs:
    - targets:
        - localhost
      labels:
        job: docker
        __path__: /var/lib/docker/containers/*/*log

  pipeline_stages:
    - json:
        expressions:
          level: level
          status_code: status_code
          message: message
          stream: stream
          attrs: attrs
          tag: attrs.tag

    - labels:
        level:
        status_code:
        stream:

    - output:
        source: message

    - timestamp:
        source: time
        format: RFC3339Nano

