- name: Copy docker-compose file
  ansible.builtin.copy:
    src: /home/skyline/ansible/devops/docker-compose.yml
    dest: /root
    mode: '0644'

- name: Tear down existing services
  docker_compose:
    project_src: /root
    state: absent

- name: Create and start services
  docker_compose:
    project_src: /root
    pull: yes
  register: output

- name: Run `docker-compose up` again
  docker_compose:
    project_src: /root
    build: no
  register: output